[package]
name = "galton"
version = "0.1.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]

[dependencies]
bincode = "1.0.1"
osmpbfreader = "0.12.0"
petgraph = { version = "0.4.13", features = ["serde-1"] }
serde = "1.0"
serde_derive = "1.0"
rstar = "0.1.0"